services:
  chatbot:
    build: .
    container_name: chatbot-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./chroma_db:/app/chroma_db
    restart: unless-stopped
